### ISSUE TITLE
Byte order mark breaks scripts on Linux/MacOS

### ISSUE THREAD

**Issue by zhovner** [oe-d/control#1]
Please remove BOM from the beginning of files: 

```
[control] Lua error: /Users/a/.mpv/scripts/control.lua:1: unexpected symbol near '�'
```

Also can you please add some manual about files location. If these paths are correct?

```
.
├── script-settings
│   └── control.conf
└── scripts
    └── control.lua
```

I've tried to use `end_rewind=file` but it doesn't work. How to debug this?

**Comment by zhovner** [comment]
I found that editing `control.conf` does not work for me. When I change `end_rewind = 'file'` directly in `control.lua` it started to work.

**Comment by oe-d** [comment]
Removed the BOM.

I'm on windows, but just tried this on linux. Most things work as they should.

control.conf goes in ~/.config/mpv/script-opts (see https://mpv.io/manual/stable/#files)
